FROM node:lts-slim

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git && \
    apt-get install -y make && \
    apt-get install gcc -y && \
    apt-get install build-essential -y

#RUN apt-get install -y \ 
#    pkg-config \
#    python-dev \ 
#    python-opencv \ 
#    libopencv-dev \ 
#    libav-tools  \ 
#    libjpeg-dev \ 
#    libpng-dev \ 
#    libtiff-dev \ 
# #   libjasper-dev \ 
#    python-numpy \ 
#    python-pycurl \ 
#    python-opencv

RUN git clone https://github.com/pjreddie/darknet.git

#RUN git clone https://github.com/AlexeyAB/darknet.git

WORKDIR /darknet

#RUN sed -i 's/GPU=0.*/GPU=1/' ./Makefile
#RUN sed -i 's/OPENCV=0.*/OPENCV=1/' ./Makefile

RUN make

RUN wget https://pjreddie.com/media/files/yolov3.weights

VOLUME [ "/data" ]

COPY . /darknet

CMD node index

#RUN ./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg

#CMD cp /darknet/predictions.jpg /data

# docker run --rm -it -p 3002:3002 -v /Users/jimmy/Tmp:/data darknetyolonodeapi:latest
# require('./index')